# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_amowinter_asciiloop.py
# Created on: 2019-02-27 12:15:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
ssh_Layer1_tif = "C:\\Users\\bunny\\Documents\\gdrive\\ArcGIS\\ssh_Layer1.tif"
amo_winter_csv = "C:\\Users\\bunny\\Documents\\GitHub\\Chapter_1\\output\\env\\amo_winter.csv"
nao_winter_dbf = amo_winter_csv
ArcGIS = "C:\\Users\\bunny\\Documents\\gdrive\\ArcGIS"
I_nao_winter_year = nao_winter_dbf
year = I_nao_winter_year
month = I_nao_winter_year
winter_val__2_ = I_nao_winter_year
conout = "C:\\Users\\bunny\\Documents\\ArcGIS\\Default.gdb\\conout"
v_year___month__amo_winter_depth__asc = "C:\\Users\\bunny\\Documents\\gdrive\\ArcGIS\\climate_ascii\\%year%_%month%_amo_winter%depth%.asc"
Value = "2018"
depth = "_01"

# Process: Table to Table
arcpy.TableToTable_conversion(amo_winter_csv, ArcGIS, "nao_winter.dbf", "", "year \"year\" true true false 4 Long 0 0 ,First,#,C:\\Users\\bunny\\Documents\\GitHub\\Chapter_1\\output\\env\\amo_winter.csv,year,-1,-1;WinterAvg \"WinterAvg\" true true false 8 Double 0 0 ,First,#,C:\\Users\\bunny\\Documents\\GitHub\\Chapter_1\\output\\env\\amo_winter.csv,WinterAvg,-1,-1;WinterAvgS \"WinterAvgShifted\" true true false 8 Double 0 0 ,First,#,C:\\Users\\bunny\\Documents\\GitHub\\Chapter_1\\output\\env\\amo_winter.csv,WinterAvgShifted,-1,-1", "")

# Process: Iterate Row Selection
arcpy.IterateRowSelection_mb(nao_winter_dbf, "year #", "false")

# Process: Get Field Value (4)
arcpy.GetFieldValue_mb(I_nao_winter_year, "WinterAvgS", "Double", "0")

# Process: Get Field Value (2)
arcpy.GetFieldValue_mb(I_nao_winter_year, "month", "String", "0")

# Process: Get Field Value
arcpy.GetFieldValue_mb(I_nao_winter_year, "year", "String", "0")

# Process: Con
arcpy.gp.Con_sa(ssh_Layer1_tif, winter_val__2_, conout, "", "")

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(conout, v_year___month__amo_winter_depth__asc)

